### ISSUE TITLE
Linter does not ignore MDX content beyond simple tags

### ISSUE THREAD

**Issue by mghill** [PlaceOS/docs#27]
Referring to [this commit](https://github.com/PlaceOS/docs/pull/25/checks?sha=7db2d46c9cba75ee54790349c8862c29f82ef8ed), the linter finds issue with the imports at the top (which can presumably be wrapped in a tag of some sort?), and the Tabs declaration on line 21 (which is only slightly more complex than an open/close tag) . The closing tags etc have no issues.

**Comment by kimburgess** [comment]
This is due to the current parser only supporting markdown, as opposed to MDX.

A quick solution should be possible via the pre-existing [filter-rule-allow-list](https://github.com/textlint/textlint-filter-rule-allowlist). This can be configured with a set of RegExp's that matches the import statements, as well as anything resembling JSX components.

A nicer / long term solution will likely be a mdx plug-in. There are existing ones for both [html](https://github.com/textlint/textlint-plugin-html) and [JSX](https://github.com/hata6502/textlint-plugin-jsx) which may provide useful references.

I'll get the filter-rule approach up and running, then we can go down that second route if there's anything that can't be expressed that way, or there's another need for it.

**Comment by kimburgess** [comment]
After sleeping on this - do we actually want/need to mix in MDX here at all?

Doing so leaks pieces of the docs renderer into the docs content. Looking through the current set of [MDX features in Docusaurus](https://v2.docusaurus.io/docs/2.0.0-alpha.69/markdown-features), Tabs look to be the only item that introduces this. Admonitions, live code blocks and the other features are all just vanilla markdown with some overloaded syntax (which is still readable in raw form too).

Tabs are definitely important as they will help with progressive disclosure and keep things neat—definitely not advocating for their removal, maybe just an alternative implementation.

There is a rather useful HTML element that provides similar functionality: [`details`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details).

Writing this:
```html
<details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
</details>
```

Creates this:
<details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
</details>

The docs renderer can then be updated to transpile this into the Docusaurus `Tab` component so the end result there is still the same, but then this also stays readable if viewed elsewhere.

**Comment by kimburgess** [comment]
Closing. Linter is working correctly for _markdown_ content, but correctly erroring when passed _mdx_.

Solution to support tab groups via https://github.com/PlaceOS/docs-site/issues/13.
